name: Release on master updates

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    name: Create GitHub Draft Release with APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to fetch tags
          submodules: true  # fetch and init submodules
          persist-credentials: true  # use GITHUB_TOKEN for submodules

      - name: Ensure submodules are initialized
        shell: bash
        run: |
          set -euo pipefail
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule status

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Determine next tag
        id: next_tag
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags --quiet
          last_tag=$(git tag --list 'v*' --sort=-v:refname | head -n1)
          if [ -z "$last_tag" ]; then
            next_tag="v0.1.0"
          else
            ver=${last_tag#v}
            IFS='.' read -r major minor patch <<< "$ver"
            if [ -z "${major}" ] || [ -z "${minor}" ] || [ -z "${patch}" ]; then
              echo "::error::Last tag '$last_tag' is not in vMAJOR.MINOR.PATCH format" >&2
              exit 1
            fi
            patch=$((patch+1))
            next_tag="v${major}.${minor}.${patch}"
          fi
          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> "$GITHUB_OUTPUT"

      - name: Create and push tag (if not exists)
        id: push_tag
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ steps.next_tag.outputs.next_tag }}"
          if git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
            echo "Tag ${tag} already exists locally; ensuring it is pushed."
          else
            git tag "${tag}"
          fi
          # Push tag if not present on origin
          if git ls-remote --tags origin | grep -q "refs/tags/${tag}$"; then
            echo "Tag ${tag} already exists on origin."
            echo "created=false" >> "$GITHUB_OUTPUT"
          else
            git push origin "${tag}"
            echo "created=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Make Gradle wrapper executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build release APK
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew --version
          ./gradlew --no-daemon clean :app:assembleRelease
          echo "Listing APK outputs:"
          ls -alh app/build/outputs/apk/release || true

      - name: Create GitHub Draft Release (new tag)
        if: ${{ steps.push_tag.outputs.created == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.next_tag }}
          name: Release ${{ steps.next_tag.outputs.next_tag }}
          draft: true
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Draft Release (existing tag)
        if: ${{ steps.push_tag.outputs.created != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.next_tag }}
          name: Release ${{ steps.next_tag.outputs.next_tag }}
          draft: true
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/*.apk
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
